from __future__ import annotations
import asyncio
import os
import tempfile
import time
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Tuple

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

router = APIRouter()

# =========
# Models
# =========

class CookieItem(BaseModel):
    name: str
    value: str
    domain: str
    path: str = "/"
    secure: bool = False
    httpOnly: Optional[bool] = None
    hostOnly: Optional[bool] = None
    session: Optional[bool] = None
    expirationDate: Optional[float] = None  # segundos
    expires: Optional[float] = None         # segundos
    expiresUTC: Optional[float] = None      # milissegundos em alguns dumps

class ConvertPayload(BaseModel):
    cookies: List[CookieItem]

class DownloadPayload(BaseModel):
    urls: List[str] = Field(..., description="Lista de URLs para o yt-dlp baixar")
    output_dir: Optional[str] = Field(None, description="Diretório de saída. Se vazio, usa a pasta atual.")
    cookies_txt: Optional[str] = Field(None, description="Conteúdo do cookies.txt (Netscape). Opcional")
    concurrency: int = Field(3, ge=1, le=10, description="Número de downloads em paralelo (1-10)")
    # --- controles de ritmo (freios) ---
    limit_rate: Optional[str] = Field(None, description="Teto de velocidade por download. Ex: '5M', '800K'. Vazio = sem limite.")
    sleep_interval: int = Field(0, ge=0, le=60, description="Segundos de pausa entre vídeos. 0 = sem pausa.")
    concurrent_fragments: int = Field(4, ge=1, le=16, description="Fragmentos (conexões) simultâneos por vídeo.")
    extra_args: Optional[List[str]] = Field(
        default=None,
        description="Argumentos extras do yt-dlp. Ex: [\"-f\",\"bv+ba/b\"]"
    )

# =========
# Cookie conversion
# =========

def _as_bool(v: Any) -> bool:
    if isinstance(v, bool):
        return v
    if isinstance(v, (int, float)):
        return bool(v)
    if isinstance(v, str):
        return v.strip().lower() in {"1", "true", "yes", "y", "t"}
    return False

def _pick(d: Dict[str, Any], *keys: str, default=None):
    for k in keys:
        if k in d:
            return d[k]
    return default

def _cookie_to_tuple(c: CookieItem) -> Tuple[str, str, str, str, int, str, str]:
    name = c.name or ""
    value = c.value or ""
    domain = (c.domain or "").strip()
    path = c.path or "/"
    secure = "TRUE" if c.secure else "FALSE"

    host_only = bool(c.hostOnly) if c.hostOnly is not None else False
    # include_subdomains: FALSE se hostOnly ou se domain não começar com ponto.
    include_sub = "FALSE" if host_only or (domain and not domain.startswith(".")) else "TRUE"

    # Expiração: tenta várias chaves; defaults p/ 0 (sessão)
    exp = 0
    for cand, mult in ((c.expires, 1), (c.expirationDate, 1), (c.expiresUTC, 1/1000)):
        if cand:
            try:
                v = int(float(cand) * mult)
                if v > 0:
                    exp = v
                    break
            except Exception:
                pass

    # Domínio com ponto se include_sub == TRUE
    line_domain = domain if include_sub == "FALSE" else (domain if domain.startswith(".") else f".{domain}")
    return (line_domain, include_sub, path, secure, exp, name, value)

def cookies_to_netscape_lines(cookies: Iterable[CookieItem]) -> List[str]:
    return [f"{d}\t{sub}\t{p}\t{s}\t{e}\t{n}\t{v}" for (d, sub, p, s, e, n, v) in (_cookie_to_tuple(c) for c in cookies)]

# =========
# Endpoints: cookies
# =========

@router.post("/convert-cookies")
def convert_cookies(payload: ConvertPayload):
    try:
        lines = cookies_to_netscape_lines(payload.cookies)
        header = "# Netscape HTTP Cookie File\n# Generated by 4linux-downloader\n"
        return {"cookies_txt": header + "\n".join(lines) + "\n"}
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Falha ao converter cookies: {e}")

# =========
# yt-dlp runner (concorrente)
# =========

@dataclass
class JobResult:
    url: str
    returncode: int
    stdout: str
    stderr: str
    started_at: float
    ended_at: float

def _build_command(
    url: str,
    *,
    output_dir: Optional[str],
    cookies_file: Optional[str],
    extra_args: Optional[List[str]],
    concurrent_fragments: int = 4,
    limit_rate: Optional[str] = None,
    sleep_interval: int = 0,
) -> List[str]:
    cmd: List[str] = ["yt-dlp"]

    # Flags "resilientes" padrão.
    # OBS: -N é o atalho de --concurrent-fragments (mesma flag), então usamos só uma.
    frags = max(1, int(concurrent_fragments or 1))
    cmd += [
        "--no-warnings",
        "--ignore-config",
        "--no-continue",            # ou troque para --continue, se preferir retomar
        "--retries", "10",
        "--fragment-retries", "10",
        "--concurrent-fragments", str(frags),
    ]

    # Freios opcionais (ritmo / discrição com o servidor de origem)
    if limit_rate:
        cmd += ["--limit-rate", str(limit_rate)]
    if sleep_interval and int(sleep_interval) > 0:
        cmd += ["--sleep-interval", str(int(sleep_interval))]

    # Respeita output_dir, mas deixa yt-dlp nomear arquivos
    if output_dir:
        cmd += ["-P", output_dir]

    # cookies.txt se fornecido
    if cookies_file:
        cmd += ["--cookies", cookies_file]

    # argumentos extras customizados
    if extra_args:
        cmd += list(extra_args)

    cmd.append(url)
    return cmd

async def _run_one(
    url: str,
    sem: asyncio.Semaphore,
    *,
    output_dir: Optional[str],
    cookies_file: Optional[str],
    extra_args: Optional[List[str]],
    concurrent_fragments: int = 4,
    limit_rate: Optional[str] = None,
    sleep_interval: int = 0,
) -> JobResult:
    async with sem:
        started = time.time()
        cmd = _build_command(
            url,
            output_dir=output_dir,
            cookies_file=cookies_file,
            extra_args=extra_args,
            concurrent_fragments=concurrent_fragments,
            limit_rate=limit_rate,
            sleep_interval=sleep_interval,
        )
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        out_b, err_b = await proc.communicate()
        ended = time.time()
        return JobResult(
            url=url,
            returncode=proc.returncode,
            stdout=out_b.decode("utf-8", errors="ignore"),
            stderr=err_b.decode("utf-8", errors="ignore"),
            started_at=started,
            ended_at=ended,
        )

async def run_ytdlp_async(
    urls: List[str],
    *,
    concurrency: int = 3,
    output_dir: Optional[str] = None,
    cookies_txt: Optional[str] = None,
    extra_args: Optional[List[str]] = None,
    limit_rate: Optional[str] = None,
    sleep_interval: int = 0,
    concurrent_fragments: int = 4,
) -> Dict[str, Any]:
    if not urls:
        raise ValueError("Nenhuma URL fornecida.")

    # Garante diretório de saída
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    # Se veio cookies_txt, grava temporário
    tmp_cookie_path = None
    if cookies_txt:
        fd, tmp_cookie_path = tempfile.mkstemp(prefix="cookies_", suffix=".txt")
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(cookies_txt)

    sem = asyncio.Semaphore(concurrency)
    started = time.time()
    try:
        tasks = [
            _run_one(
                u, sem,
                output_dir=output_dir,
                cookies_file=tmp_cookie_path,
                extra_args=extra_args,
                concurrent_fragments=concurrent_fragments,
                limit_rate=limit_rate,
                sleep_interval=sleep_interval,
            )
            for u in urls
        ]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        ok = True
        jobs: List[Dict[str, Any]] = []
        for r in results:
            if isinstance(r, Exception):
                ok = False
                jobs.append({"url": "unknown", "error": str(r)})
            else:
                ok = ok and (r.returncode == 0)
                jobs.append({
                    "url": r.url,
                    "returncode": r.returncode,
                    "duration": round(r.ended_at - r.started_at, 3),
                    "stdout": r.stdout[-4000:],  # limita o tamanho no JSON
                    "stderr": r.stderr[-4000:],
                })

        return {
            "ok": ok,
            "count": len(urls),
            "concurrency": concurrency,
            "output_dir": output_dir or os.getcwd(),
            "duration": round(time.time() - started, 3),
            "jobs": jobs,
        }
    finally:
        if tmp_cookie_path:
            try:
                os.remove(tmp_cookie_path)
            except OSError:
                pass

# =========
# Endpoints: download
# =========

@router.post("/download")
async def download(payload: DownloadPayload):
    try:
        result = await run_ytdlp_async(
            urls=payload.urls,
            concurrency=payload.concurrency,
            output_dir=payload.output_dir,
            cookies_txt=payload.cookies_txt,
            extra_args=payload.extra_args,
            limit_rate=payload.limit_rate,
            sleep_interval=payload.sleep_interval,
            concurrent_fragments=payload.concurrent_fragments,
        )
        return result
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Falha no download: {e}")
